name: Daily Audit News Report

on:
  schedule:
    # 한국 시간 오전 11시 10분 (UTC 02:10)  # 23시 3분 (UTC) / 한국시간 오전 8시 3분
    - cron: '3 4 * * *'  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install requests beautifulsoup4

      - name: Run Python Script
        env:
          NAVER_ID: ${{ secrets.NAVER_CLIENT_ID }}
          NAVER_SECRET: ${{ secrets.NAVER_CLIENT_SECRET }}
          EMAIL_PW: ${{ secrets.EMAIL_PW }}
          TARGET_EMAILS: ${{ secrets.TARGET_EMAILS }}
        run: python audit_report.py
